server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**,/api/admin/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
        - id: user-auth-service
          uri: lb://user-auth-service
          predicates:
            - Path=/api/auth/**,/api/users/**

